name: Update a pinned gist with RSS feed
on:
  schedule:
    - cron: "*/5 * * * *" # Se ejecuta cada 5 minutos!
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
