name: Update a pinned gist with RSS feed
on:
  schedule:
    - cron: "*/5 * * * *" # Se ejecuta cada 5 minutos!
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 05c75f4491d78792c767ac8bc07d7e46
      RSS_URL: https://en.wikipedia.org/w/api.php?action=featuredfeed&feed=featured&feedformat=rss
