name: Update a pinned gist with an RSS/Atom feed
on:
  schedule:
    - cron: "*/5 * * * *" # Se ejecuta cada 5 minutos!
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: albertocc/feed-box@master
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 05c75f4491d78792c767ac8bc07d7e46
      RSS_URL: 'https://en.wikinews.org/w/index.php?title=Special:NewsFeed&feed=atom&categories=Published&notcategories=No%20publish%7CArchived%7CAutoArchived%7Cdisputed&namespace=0&count=30&hourcount=124&ordermethod=categoryadd&stablepages=only'
